import { wrapReportHtml, injectHeroMetrics, isUziFullReport, type ReportHeroMeta } from "./reportShell";

/** Remove UZI-Skill upstream branding from standalone report footers. */
export function stripUziBrandingFooter(html: string): string {
  if (!html?.trim()) return html;
  let out = html;
  out = out.replace(/\s*Generated by[\s\S]*?O\.o\s*<\/span>\s*<br>\s*/gi, "<br>");
  out = out.replace(/\s*<a[^>]*github\.com\/wbh604\/UZI-Skill[^>]*>[\s\S]*?<\/a>\s*<br>\s*/gi, "");
  out = out.replace(/\s*<span[^>]*>\s*POWERED BY FloatFu-true\s*<\/span>\s*/gi, "");
  return out;
}

const IFRAME_NAV_GUARD = `<script>(function(){document.addEventListener("click",function(e){var a=e.target.closest("a[href]");if(!a)return;var href=a.getAttribute("href");if(!href||href==="#")return;if(href.charAt(0)==="#"){var id=decodeURIComponent(href.slice(1));var el=document.getElementById(id);if(el){e.preventDefault();el.scrollIntoView({behavior:"smooth",block:"start"});history.replaceState(null,"","#"+id);}return;}if(/^(https?:|mailto:|tel:|javascript:)/i.test(href)){e.preventDefault();return;}e.preventDefault();var slug=href.replace(/^\\.\\/?/,"").split(/[?#]/)[0];var target=document.getElementById(slug);if(target){target.scrollIntoView({behavior:"smooth",block:"start"});history.replaceState(null,"","#"+slug);}},true);})();</script>`;

const IFRAME_SCROLL_STYLE =
  "<style>html{scroll-behavior:smooth;}section[id],div[id],article[id]{scroll-margin-top:1rem;}</style>";

/** 注入 iframe 预览所需的导航保护与滚动样式，避免侧栏点击导致 iframe 跳转到空白页 */
export function prepareHtmlForIframePreview(html: string, heroMeta?: ReportHeroMeta | null): string {
  const cleaned = stripUziBrandingFooter(html);
  if (isUziFullReport(cleaned)) {
    const injection = IFRAME_SCROLL_STYLE + IFRAME_NAV_GUARD;
    if (/<\/body>/i.test(cleaned)) {
      return cleaned.replace(/<\/body>/i, `${injection}</body>`);
    }
    if (/<\/html>/i.test(cleaned)) {
      return cleaned.replace(/<\/html>/i, `${injection}</html>`);
    }
    return cleaned + injection;
  }

  const withHero = heroMeta ? injectHeroMetrics(cleaned, heroMeta) : cleaned;
  const wrapped = wrapReportHtml(withHero);
  const injection = IFRAME_SCROLL_STYLE + IFRAME_NAV_GUARD;
  if (/<\/body>/i.test(wrapped)) {
    return wrapped.replace(/<\/body>/i, `${injection}</body>`);
  }
  if (/<\/html>/i.test(wrapped)) {
    return wrapped.replace(/<\/html>/i, `${injection}</html>`);
  }
  return wrapped + injection;
}

/** 下载用：UZI 完整报告原样保存；LLM 片段套用 reportShell，不注入 iframe 脚本 */
export function prepareHtmlForDownload(html: string, heroMeta?: ReportHeroMeta | null): string {
  if (!html?.trim()) return html;
  const cleaned = stripUziBrandingFooter(html);
  if (isUziFullReport(cleaned)) return cleaned;
  const withHero = heroMeta ? injectHeroMetrics(cleaned, heroMeta) : cleaned;
  return wrapReportHtml(withHero);
}

export type { ReportHeroMeta } from "./reportShell";
export { injectHeroMetrics } from "./reportShell";
export function extractHtmlReport(content: string): string | null {
  if (!content) return null;

  const htmlBlock = content.match(/```html\s*([\s\S]*?)```/i);
  if (htmlBlock?.[1]) {
    return htmlBlock[1].trim();
  }

  const genericBlock = content.match(/```\s*(<!DOCTYPE[\s\S]*?<\/html>[\s\S]*?)```/i);
  if (genericBlock?.[1]) {
    return genericBlock[1].trim();
  }

  const docMatch = content.match(/(<!DOCTYPE[\s\S]*<\/html>)/i);
  if (docMatch?.[1]) {
    return docMatch[1].trim();
  }

  const htmlTagMatch = content.match(/(<html[\s\S]*<\/html>)/i);
  if (htmlTagMatch?.[1]) {
    return htmlTagMatch[1].trim();
  }

  return null;
}

/** 提取 HTML 代码块之前的简短对话文本 */
export function extractChatSummary(content: string): string {
  const idx = content.search(/```html/i);
  if (idx === -1) return content;
  return content.slice(0, idx).trim();
}
