package hotmoney

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestIsTqdmProgressLineEmbeddedCR(t *testing.T) {
	line := "0%|          | 0/4 [00:00<?, ?it/s]\r                                     \r\r  0%|          | 0/4 [00:00<?, ?it/s]"
	if !IsTqdmProgressLine(line) {
		t.Fatalf("embedded CR tqdm line should be detected: %q", line)
	}
	msg := formatUZIProcessError(context.Background(), errors.New("exit status 1"), []string{line})
	if strings.Contains(msg, "%|") {
		t.Fatalf("tqdm should not leak into error: %q", msg)
	}
}

func TestStripTqdmFromErrorEmbeddedCR(t *testing.T) {
	raw := "uzi report: 0%|          | 0/4 [00:00<?, ?it/s]\r                                     \r\r  0%|          | 0/4 [00:00<?, ?it/s]"
	got := StripTqdmFromError(raw)
	if strings.Contains(got, "%|") {
		t.Fatalf("tqdm not stripped: %q", got)
	}
	if got != "UZI 报告生成失败" {
		t.Fatalf("expected generic fallback for tqdm-only error, got: %q", got)
	}
}

func TestUserFacingUZIError(t *testing.T) {
	raw := errors.New("uzi report: ModuleNotFoundError: No module named 'akshare'")
	got := UserFacingUZIError(raw)
	if !strings.Contains(got, "ModuleNotFoundError") {
		t.Fatalf("expected module error: %q", got)
	}
	tqdmErr := errors.New("uzi report: 0%|          | 0/4 [00:00<?, ?it/s]\r  2%|▏         | 1/58 [00:01<01:06,  1.17s/it]")
	got = UserFacingUZIError(tqdmErr)
	if strings.Contains(got, "%|") {
		t.Fatalf("tqdm leaked: %q", got)
	}
}

func TestStripUZIBrandingFooter(t *testing.T) {
	sample := `<footer>
    <strong>⚠️ DISCLAIMER · 免责声明</strong><br>
    本报告由 AI 模型基于公开信息生成。<br><br>
    Generated by <strong>FloatFu-true · UZI-Skill v2.2.0</strong> · 2026-06-27 10:01 · <span class="oo-eye">O.o</span><br>
    <a href="https://github.com/wbh604/UZI-Skill" target="_blank">⭐ GitHub · 点击查看最新版本 → github.com/wbh604/UZI-Skill</a><br>
    <span style="font-size:10px">POWERED BY FloatFu-true</span>
  </footer>`
	got := stripUZIBrandingFooter(sample)
	for _, bad := range []string{
		"Generated by",
		"FloatFu-true · UZI-Skill",
		"github.com/wbh604/UZI-Skill",
		"POWERED BY FloatFu-true",
	} {
		if strings.Contains(got, bad) {
			t.Fatalf("expected branding removed, still contains %q in:\n%s", bad, got)
		}
	}
	if !strings.Contains(got, "免责声明") {
		t.Fatalf("disclaimer should remain: %s", got)
	}
}

func TestFindLatestUZIStandaloneHTML(t *testing.T) {
	root := filepath.Join("..", "..", "..", "UZI-Skill")
	if _, err := os.Stat(root); err != nil {
		t.Skip("UZI-Skill not present")
	}
	abs, _ := filepath.Abs(root)
	path := findLatestUZIStandaloneHTML(abs, "600519.SH")
	if path == "" {
		t.Skip("no cached 600519.SH report")
	}
	if !strings.HasSuffix(path, "full-report-standalone.html") {
		t.Fatalf("unexpected path: %s", path)
	}
}
